rewrite

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -16,37 +16,71 @@ BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
 
-source $LIB_DIR/common.sh
-source $LIB_DIR/failures.sh
-source <(curl --retry 3 -fsSL $BUILDPACK_STDLIB_URL)
+PROJECT_DIR="$(cat $ENV_DIR/PROJECT_DIR)"
+INSTALL_DIR=$BUILD_DIR
+BUILD_DIR=$BUILD_DIR/$PROJECT_DIR
+
+
+# By default gradle will write its cache in `$BUILD_DIR/.gradle`. Rather than
+# using the --project-cache-dir option, which muddies up the command, we
+# symlink this directory to the cache.
+create_project_cache_symlink() {
+  local buildpackCacheDir="${1:?}/.gradle-project"
+  local projectCacheLink="${2:?}/.gradle"
+  if [ ! -d "$projectCacheLink" ]; then
+    mkdir -p "$buildpackCacheDir"
+    ln -s "$buildpackCacheDir" "$projectCacheLink"
+    trap "rm -f $projectCacheLink" EXIT
+  fi
+}
+
+install_jdk() {
+  local install_dir=${1:?}
+  local cache_dir=${2:?}
+
+
+  JVM_COMMON_BUILDPACK=${JVM_COMMON_BUILDPACK:-https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/jvm.tgz}
+  mkdir -p /tmp/jvm-common
+  curl --retry 3 --silent --location $JVM_COMMON_BUILDPACK | tar xzm -C /tmp/jvm-common --strip-components=1
+  source /tmp/jvm-common/bin/util
+  source /tmp/jvm-common/bin/java
+  source /tmp/jvm-common/opt/jdbc.sh
+
+
+
+  install_java_with_overlay "${install_dir}" "${cache_dir}"
+
+}
+
+
+# Usage: $ _env-blacklist pattern
+# Outputs a regex of default blacklist env vars.
+_env_blacklist() {
+  local regex=${1:-''}
+  if [ -n "$regex" ]; then
+    regex="|$regex"
+  fi
+  echo "^(PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH$regex)$"
+}
+
+# Usage: $ export-env ENV_DIR WHITELIST BLACKLIST
+# Exports the environment variables defined in the given directory.
+export_env() {
+  local env_dir=${1:-$ENV_DIR}
+  local whitelist=${2:-''}
+  local blacklist="$(_env_blacklist $3)"
+  if [ -d "$env_dir" ]; then
+    for e in $(ls $env_dir); do
+      echo "$e" | grep -E "$whitelist" | grep -qvE "$blacklist" &&
+      export "$e=$(cat $env_dir/$e)"
+      :
+    done
+  fi
+}
 
 export_env $ENV_DIR "." "JAVA_OPTS|JAVA_TOOL_OPTIONS"
 
-if has_stage_task $BUILD_DIR; then
-  mcount "task.stage"
-  DEFAULT_GRADLE_TASK="stage"
-elif is_spring_boot $BUILD_DIR; then
-  if is_webapp_runner $BUILD_DIR; then
-    echo "-----> Spring Boot and Webapp Runner detected"
-    mcount "task.webapprunner"
-  else
-    echo "-----> Spring Boot detected"
-    mcount "task.spring"
-  fi
-  DEFAULT_GRADLE_TASK="build -x test"
-elif is_ratpack $BUILD_DIR; then
-  echo "-----> Ratpack detected"
-  mcount "task.ratpack"
-  DEFAULT_GRADLE_TASK="installDist -x test"
-else
-  DEFAULT_GRADLE_TASK="stage"
-fi
-
-if [ -z "$GRADLE_TASK" ]; then
-  GRADLE_TASK="${DEFAULT_GRADLE_TASK}"
-fi
-
-install_jdk "${BUILD_DIR}" "${CACHE_DIR}"
+install_jdk "${INSTALL_DIR}" "${CACHE_DIR}"
 
 export GRADLE_OPTS=${GRADLE_OPTS-"-Dorg.gradle.daemon=false -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false"}
 
@@ -55,38 +89,21 @@ export GRADLE_USER_HOME=${GRADLE_USER_HOME:-$CACHE_DIR/.gradle}
 
 create_project_cache_symlink "$CACHE_DIR" "$BUILD_DIR"
 
-if [ ! -f $BUILD_DIR/gradlew ] ; then
-  mcount "wrapperless"
-  echo "-----> Installing Gradle Wrapper..."
-  echo "       WARNING: Your application does not have it's own gradlew file."
-  echo "       We'll install one for you, but this is a deprecated feature and"
-  echo "       in the future may not be supported."
-  cp -rn ${OPT_DIR}/wrapper/* ${BUILD_DIR}
-fi
-BUILDCMD="./gradlew"
-chmod +x ${BUILD_DIR}/gradlew
-
-BUILDCMD="$BUILDCMD $GRADLE_TASK"
+BUILDCMD="./gradlew build -x test"
 
 cd $BUILD_DIR
 
-[ -n "$(find . -type f -name "*.kt")" ] && mcount "kotlin.source"
-[ -n "$(find . -type f -name "*.groovy")" ] && mcount "groovy.source"
-
 # build app
-echo "-----> Building Gradle app..."
 echo "-----> executing $BUILDCMD"
 
-buildLogFile=$(create_build_log_file)
+$BUILDCMD 2>&1
 
-let start=$(nowms)
-$BUILDCMD 2>&1 | output $buildLogFile
-
-if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-  handle_gradle_errors $buildLogFile
+if [ $? -ne 0 ]; then
+  echo "gradle build failed. aborting"
+  exit 1
 fi
 
 # https://github.com/heroku/heroku-buildpack-gradle/issues/49
 rm -rf "$CACHE_DIR/.gradle/nodejs"
 
-mtime "build.time" "${start}"
+mv $BUILD_DIR/build $INSTALL_DIR
